name: ecommerce
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

    #--------------------------------------Packages start-------------------------------------#


  #Utility Packages
  http: ^1.2.2
  intl: ^0.19.0
  logger: ^2.4.0
  url_launcher: ^6.3.0
  flutter_native_splash: ^2.4.1
  smooth_page_indicator: ^1.2.0+3
  lottie: ^3.1.2
  connectivity_plus: ^5.0.1





  #icons
  cupertino_icons: ^1.0.6
  iconsax: ^0.0.8

  #Fonts
  google_fonts: ^4.0.4


  #state management:
  get: ^4.6.6
  get_storage: ^2.1.1

  #Product Specific
  readmore: ^3.0.0
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1


  #Firebase
  google_sign_in: ^6.2.1
  firebase_auth: ^5.2.0
  firebase_core: ^3.4.0
  cloud_firestore: ^5.3.0




  #--------------------------------------Packages end-------------------------------------#


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0



flutter:


  uses-material-design: true
  assets:
    - assets/images/on_boarding_images/
    - assets/logos/
    - assets/icons/categories/
    - assets/images/animations/
    - assets/images/banners/
    - assets/images/products/
    - assets/icons/brands/
    - assets/images/user/user.png
    - assets/images/reviews/
    - assets/icons/payment_methods/


  #----------------Fonts----------------------#



